#ifndef COMMANDS_H_
#define COMMANDS_H_

//Control commands
#define MESSAGE_TERMINATOR 0
#define MESSAGE_HEAD 204

//Serial command set from UI to controller
#define SET_TARGET_LIVING_TEMP 1
#define SET_TARGET_UPSTAIRS_TEMP 2
#define SET_TARGET_BASEMENT_TEMP 3

#define ACK_SET_TARGET_LIVING_TEMP 21
#define ACK_SET_TARGET_UPSTAIRS_TEMP 22
#define ACK_SET_TARGET_BASEMENT_TEMP 23

//Serial command set from controller to UI
#define COMMUNICATE_LIVING_TEMP 4
#define COMMUNICATE_UPSTAIRS_TEMP 5
#define COMMUNICATE_BASEMENT_TEMP 6
#define COMMUNICATE_EXTERNAL_TEMP 7
#define COMMUNICATE_HEATING_MODE 8

#define ACK_COMMUNICATE_LIVING_TEMP 24
#define ACK_COMMUNICATE_UPSTAIRS_TEMP 25
#define ACK_COMMUNICATE_BASEMENT_TEMP 26
#define ACK_COMMUNICATE_EXTERNAL_TEMP 27
#define ACK_COMMUNICATE_HEATING_MODE 28

// The states of the UI messaging
#define AWAITING_COMMAND 0
#define RECEIVING_COMMAND 1
#define PROCESSING_COMMAND 2

// The display modes of the UI
#define DISPLAY_MODE_BASE 1
#define DISPLAY_MODE_EXTERNAL 2

#endif /*COMMANDS_H_*/
